spring.datasource.url=jdbc:postgresql://localhost:5432/booking3
spring.datasource.username=tumekie
spring.datasource.password=Tum3k!3B

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=omarblackwood25@gmail.com
spring.mail.password=xnxy tccx cbnx xazq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
